


select * from customer limit 20

--Q1. What is the totasl revenue generated by male vs female customers?
select gender, SUM(purchase_amount) as revenue
from customer
group by gender

--Q2. Which customers used discount but still spent more than the average purchase amount?
select customer_id, purchase_amount
from customer
where discount_applied = 'Yes' and purchase_amount >= (select AVG(purchase_amount) from customer)

--Q3. Which are the top 5 products with highest average review rating?
select item_purchased, ROUND(AVG(review_rating::numeric), 2) as average_review_rating
from customer
group by item_purchased
order by avg(review_rating) desc
limit 5;

--Q4.Compare the average purchase amount between standard and express shipping.
select shipping_type, ROUND(AVG(purchase_amount), 2) as averaage_purchase_amount
from customer
where shipping_type in ('Standard', 'Express')
group by shipping_type

--Q5. Do subscribed customers spend more? Compare average spend and total revenue between
--subscribers and non suscribers.
select subscription_status, count(customer_id) as total_customers,
ROUND(AVG(purchase_amount), 2) as average_spend, Round(SUM(purchase_amount), 2) as total_revenue
from customer
group by subscription_status
order by total_revenue, average_spend desc;

--Q6. Which 5 products have the highest percentage of purchases with discounts applied?
select item_purchased, ROUND(100 * SUM(CASE 
WHEN discount_applied = 'Yes' THEN 1 
ELSE 0 END)/COUNT(*), 2) as discount_rate
from customer
group by item_purchased
order by discount_rate desc
limit 5;

--Segment customers into new, returning and loyal based on their previous purchases, 
--and show the count of each segment.
with customer_type as (select customer_id, previous_purchases,
CASE 
WHEN previous_purchases = 1 THEN 'New' 
WHEN previous_purchases BETWEEN 2 AND 10 THEN 'Returning'
ELSE 'Loyal'
END as customer_segment
from customer) 

select customer_segment, count(*) as number_of_customers
from customer_type
group by customer_segment

--What are the top 3 most purchased products within each category?
with item_counts as (select category, item_purchased, COUNT(customer_id) as total_orders,
ROW_NUMBER() over(partition by category order by count(customer_id) desc)
as item_rank
from customer
group by category, item_purchased
) 

select item_rank, category, item_purchased, total_orders
from item_counts
where item_rank <= 3; 

--Are customers who are repeat buyers(more than 5 previous purchases) also likely to subscribe?
select COUNT(customer_id) as repeat_buyers,
subscription_status
from customer
where previous_purchases >= 5 
group by subscription_status

--What is the revenue contribution of each age group?
select age_group, COUNT(customer_id) as total_customers,  
SUM(purchase_amount) as revenue_contribution
from customer
group by age_group
order by revenue_contribution desc